---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
metadata:
  name: release-name-traefik
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: release-name-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-10.20.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: release-name
      annotations:
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: release-name
      ports:
      - port: 80
        name: web
        targetPort: "web"
        protocol: TCP
      - port: 443
        name: websecure
        targetPort: "websecure"
        protocol: TCP
