---
# Source: traefik/templates/rbac/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.20.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-traefik
subjects:
  - kind: ServiceAccount
    name: release-name-traefik
    namespace: kube-system
