---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: release-name-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.20.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
  annotations:
